services:
  - type: web
    name: solarexpress-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: TICKET_SALE_ADDRESS
        sync: false
      - key: SOLAREXPRESS_TICKET_ADDRESS
        sync: false
      - key: BOOKING_HISTORY_ADDRESS
        sync: false
